version: '3.3'

services:
  server:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home:/home
      - /etc:/etc
    restart: always
    ports:
      - 80:5000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "multifolder"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "6010"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db