version: '3.3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home:/home
      - /etc:/etc
      - ./server/settings_app:/server/settings_app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "multifolder"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "6010"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db