version: '3.9'

services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:1111
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 6010